spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nbcam
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

## ???? ??? ???
jwt:
  secret:
    key: fsadfsadflsadjfl123123123123l2kj3l13j2l313l21j3l12jsd


logging:
  level:
    root: info                       # ✅ 전체 로그 기본 레벨 유지 (error, warn 포함)
    org.hibernate.SQL: debug         # SQL 로그
    org.hibernate.orm.jdbc.bind: trace  # 바인딩된 파라미터 출력